# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042fed9f8b116f95c8443648b6678f787d3240840f0a5dc45a494e2f40554b8cf7df8607f97f00566d68060065c88c639486a71ae7b87460a8d89d209564c73d

test:
  secret_key_base: 8372409f22e06fce7787756babd7ef949bf4168c829f8fc1affd7a1590c5e4e5e553424969f278bcbe76c8eb8c517d35b68ac620529c434afb774fa651492acd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
